### ISSUE TITLE
Nuxt 3 support ?

### ISSUE THREAD

**Issue by jd1378** [alireza-ab/persian-date#2]
currently cannot use module with nuxt 3, is there any update planned ?

**Comment by alireza-ab** [comment]
Hi @jd1378 

Adding nuxt 3 support to the module is not a very good idea but you can easily make `usePersianDate.ts` composable with this code:
```ts
import PersianDate from '@alireza-ab/persian-date';

export default function (
  ...args: ConstructorParameters<typeof PersianDate>
): PersianDate {
  return new PersianDate(...args);
}
```
