### ISSUE TITLE
get All Date

### ISSUE THREAD

**Issue by shahinesi** [alireza-ab/persian-date#3]
سلام وقت بخیر
من چطور میتونم شروع و پایان روز هر ماه رو بدست بیارم به صورت یکجا؟
ایا تابعی وجود دارد که بعد از .addMonth() درج شود و شروع و پایان تاریخ ماه را برگرداند؟
به طور مثال که با حلقه این عدد رو بدست آوردم.
.
(اول و آخر هر ماه شمسی تبدیل به ماه میلادی شده)

2023-03-21T00:00:00.0000000
2023-04-20T23:59:59.9999999

2023-04-21T00:00:00.0000000
2023-05-21T23:59:59.9999999

2023-05-22T00:00:00.0000000
2023-06-21T23:59:59.9999999

2023-06-22T00:00:00.0000000
2023-07-22T23:59:59.9999999

.
.
.
.
.
.

**Comment by alireza-ab** [comment]
سلام وقت شما بخیر
https://alireza-ab.ir/persian-date/set-and-get#start-of
این لینک رو مطالعه کنید به نظرم همین ویژگیه که گفتین

**Comment by shahinesi** [comment]
با همین روش اتفاقات بدست آوردم با حلقه فور
ولی میخواستم بدونم ایا تابعی نیست که کل این روز به صورت یکجا بده؟

**Comment by alireza-ab** [comment]
خیر
اگه مسئله تون رو کامل متوجه شده باشم باید خروجی تون رو با حلقه بگیرید
