### ISSUE TITLE
خطا در تبدیل تاریخ از لاراول

### ISSUE THREAD

**Issue by nonomaxxis** [alireza-ab/persian-date#4]
سلام و خسته نباشید. اول تشکر از کتابخانه عالی که تهیه کردید.

در زمان تبدیل از api های لاراول با خطا مواجه می شویم.
![image](https://github.com/alireza-ab/persian-date/assets/6130447/b477988d-c1dc-4b43-9af9-0f1771dd119a)

علاوه بر اینکه تاریخ را نامعتبر میگه، برای اونایی که تبدیل میکنه هم اشتباه انجام میده.

**Comment by alireza-ab** [comment]
سلام @nonomaxxis 
وقت بخیر
ممنون از شما. لطف دارید.
متاسفانه این فرمت پشتیبانی نمیشه. اگه امکان تغییر فرمت براتون وجود داره فرمت رو تغییر بدین یا اینجوری استفاده کنید:
```js
const date = "2023-12-22T21:32:06.000000Z";
const newDate = date.slice(0,19).replace("T"," "); // 2023-12-22 21:32:06

new PersianDate(newDate, "gregorian")
```
